### ISSUE TITLE
Concerns with Code Signing Requirement

### ISSUE THREAD

**Issue by mitchelsellers** [dotnet-foundation/project-maturity-model#18]
Looking at the proposed Project Maturity Model, there is a requirement for strong name signing of projects. 

The DNN Project has looked into this in the past, and for many reasons, we have elected in the past that we cannot support this without massive changes to our infrastructure.  Now, if we are missing something, we are more than willing to be educated.  However, we have encountered issues with the fact that we consume, dynamically, and through other methods, assemblies from many sources, including custom extensions created by others that we reflection load.

**Comment by richlander** [comment]
There is no requirement for strong name signing. [Package signing](https://docs.microsoft.com/en-us/nuget/reference/signed-packages-reference) is required at [level 3](https://github.com/dotnet-foundation/project-maturity-model/blob/master/maturity-ladder.md#level-3----high-quality-project).

Package signing has no impact on the scenarios you are referencing. They are related to strong named signing.

**Comment by jongalloway** [comment]
I think we need to explicitly call this out, since it's very easy to misread it. Will send a PR.

**Comment by mitchelsellers** [comment]
Ah that would explain it, yup I misread
