### ISSUE TITLE
Maturity ladder relationship to community

### ISSUE THREAD

**Issue by daveaglick** [dotnet-foundation/project-maturity-model#3]
I like the ideas around the proposed maturity ladder as it relates to an individual project. However, it appears to be almost entirely focused on how the project is executed and misses what I think is an opportunity to define maturity partly in the context of a project’s community. In other words, the maturity of a project isn’t just about what the maintainers of that project are doing and how they relate to the community, but also what the community is doing on it’s own and how it relates amongst itself. For example, a “mature” project might include a robust ecosystem of blog posts and community support resources irrespective of anything provided by the maintainers directly.

I also want to loop in @SeanKilleen since he’s done some work and thinking in this area. His OSS Participation Maturity Model described at https://awider.net/ focuses on maturity as it relates to participation by consumers, but I think there are some good ideas there that could be adapted to this maturity model as well.

**Comment by richlander** [comment]
I agree. That's what the first "Health" characteristic for [level 3](https://github.com/dotnet-foundation/project-maturity-model/blob/master/maturity-ladder.md#level-3----high-quality-project) is intended to talk to, as follows:

> The ecosystem has adopted this project at a significant scale, demonstrated by one or more key metrics, such as package downloads, number of dependent projects on GitHub, or community activity on the project repo(s).

Certainly, the community activity might not be "on" the community repo. If we change the text to "on or related to", does that cover it?

I hadn't seen that site before. That's looks cool, and I like the name. The whole point of this pilot period is to entertain good work and ideas that already exist.

**Comment by daveaglick** [comment]
Ah, somehow totally missed the external community callout there (it’s obvious, I just didn’t see it). Yeah, that’s definitely similar to what I was thinking.

> If we change the text to "on or related to", does that cover it?

I think that one little change could be a big improvement. A project doesn’t exist in isolation and maturity is partly measured by what happens within the community and totally outside the control of the project IMO.
